# Generated by Django 4.2.6 on 2023-10-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_type',
            field=models.CharField(choices=[('error', 'Error'), ('new_feature', 'New Feature')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bug',
            name='report_date',
            field=models.DateField(),
        ),
    ]
